import { readFile,writeFile } from "node:fs/promises";
import { resolve } from "node:path";
const root=resolve(import.meta.dirname,"../.."),dir=resolve(root,"src/data");
const STATS=["intelligence","creativity","emotionalControl","empathy","social","communication","ambition","discipline","professionalism","financialSense","risk","luck","energy","humor","chaos"];
const targets={careers:200,classes:150,powers:150,weaknesses:150,abilities:150,workStyles:150,animals:150,synergyRules:200};
const read=async n=>JSON.parse(await readFile(resolve(dir,`${n}.json`),"utf8")); const write=(n,v)=>writeFile(resolve(dir,`${n}.json`),`${JSON.stringify(v,null,2)}\n`);
function hash(s){let h=2166136261;for(const c of s){h^=c.codePointAt(0);h=Math.imul(h,16777619)}return h>>>0}
function profile(id,low=false){const seed=hash(id),p={};let c=seed%STATS.length;for(let i=0;Object.keys(p).length<6;i++){c=(c+3+(seed%9)+i)%STATS.length;const k=STATS[c];if(k in p)continue;const raw=(seed>>>((i%4)*5))+i*37;p[k]=low?8+(raw%67):24+(raw%71)}return p}
function add(current,candidates,target,label){const ids=new Set(current.map(x=>x.id)),fresh=candidates.filter(x=>!ids.has(x.id)),need=target-current.length;if(need<0||fresh.length<need)throw new Error(`${label}: ${fresh.length} nouveautés pour ${need} nécessaires`);const out=[...current,...fresh.slice(0,need)];if(new Set(out.map(x=>x.id)).size!==out.length)throw new Error(`${label}: doublon`);return out}
function combos(prefix,left,right,key="idealProfile"){const out=[];for(const a of left)for(const b of right){const id=`${prefix}_${a[0]}_${b[0]}`;out.push({id,name:{en:`${a[1]} ${b[1]}`,fr:`${a[2]} ${b[2]}`,es:`${a[3]} ${b[3]}`},[key]:profile(id,key==="lowProfile"),tags:["expanded_v2",a[0],b[0]]})}return out}
const careerA=[["data","Data","Données","Datos"],["security","Security","Sécurité","Seguridad"],["automation","Automation","Automatisation","Automatización"],["research","Research","Recherche","Investigación"],["operations","Operations","Opérations","Operaciones"],["product","Product","Produit","Producto"],["community","Community","Communauté","Comunidad"],["experience","Experience","Expérience","Experiencia"],["systems","Systems","Systèmes","Sistemas"],["content","Content","Contenu","Contenido"],["logistics","Logistics","Logistique","Logística"],["sustainability","Sustainability","Durabilité","Sostenibilidad"],["quality","Quality","Qualité","Calidad"],["finance","Finance","Finance","Finanzas"],["education","Education","Éducation","Educación"],["health","Health","Santé","Salud"],["media","Media","Médias","Medios"],["events","Events","Événements","Eventos"],["accessibility","Accessibility","Accessibilité","Accesibilidad"],["innovation","Innovation","Innovation","Innovación"]];
const careerB=[["analyst","Analyst","Analyste","Analista"],["coordinator","Coordinator","Coordinateur","Coordinador"],["specialist","Specialist","Spécialiste","Especialista"],["consultant","Consultant","Consultant","Consultor"],["designer","Designer","Concepteur","Diseñador"],["manager","Manager","Responsable","Gerente"],["researcher","Researcher","Chercheur","Investigador"],["strategist","Strategist","Stratège","Estratega"],["technician","Technician","Technicien","Técnico"],["advisor","Advisor","Conseiller","Asesor"],["producer","Producer","Producteur","Productor"],["facilitator","Facilitator","Facilitateur","Facilitador"]];
const classA=[["chaotic","Chaotic","Chaotique","Caótico"],["methodical","Methodical","Méthodique","Metódico"],["relentless","Relentless","Tenace","Implacable"],["diplomatic","Diplomatic","Diplomate","Diplomático"],["curious","Curious","Curieux","Curioso"],["stoic","Stoic","Stoïque","Estoico"],["social","Social","Social","Social"],["improvised","Improvised","Improvisé","Improvisado"],["strategic","Strategic","Stratégique","Estratégico"],["patient","Patient","Patient","Paciente"],["restless","Restless","Agité","Inquieto"],["precise","Precise","Précis","Preciso"],["bold","Bold","Audacieux","Audaz"],["quiet","Quiet","Discret","Silencioso"],["adaptive","Adaptive","Adaptatif","Adaptable"],["skeptical","Skeptical","Sceptique","Escéptico"],["optimistic","Optimistic","Optimiste","Optimista"],["pragmatic","Pragmatic","Pragmatique","Pragmático"]];
const classB=[["tactician","Tactician","Tacticien","Táctico"],["explorer","Explorer","Explorateur","Explorador"],["fixer","Fixer","Dépanneur","Solucionador"],["analyst","Analyst","Analyste","Analista"],["catalyst","Catalyst","Catalyseur","Catalizador"],["guardian","Guardian","Gardien","Guardián"],["broker","Broker","Intermédiaire","Mediador"],["builder","Builder","Bâtisseur","Constructor"],["scout","Scout","Éclaireur","Explorador"],["operator","Operator","Opérateur","Operador"]];
const powerA=classA.map(([k,en,fr,es])=>[k,en,fr,es]); const powerB=[["burst","Burst","Rafale","Ráfaga"],["shield","Shield","Bouclier","Escudo"],["radar","Radar","Radar","Radar"],["override","Override","Forçage","Anulación"],["echo","Echo","Écho","Eco"],["pulse","Pulse","Impulsion","Pulso"],["anchor","Anchor","Ancre","Ancla"],["lens","Lens","Lentille","Lente"],["boost","Boost","Boost","Impulso"],["field","Field","Champ","Campo"]];
const weakA=[["notification","Notification","Notification","Notificación"],["deadline","Deadline","Deadline","Plazo"],["ambiguity","Ambiguity","Ambiguïté","Ambigüedad"],["silence","Silence","Silence","Silencio"],["comparison","Comparison","Comparaison","Comparación"],["queue","Queue","File d'attente","Cola"],["choice","Too Many Choices","Trop de choix","Demasiadas opciones"],["interruption","Interruption","Interruption","Interrupción"],["fatigue","Fatigue","Fatigue","Fatiga"],["conflict","Conflict","Conflit","Conflicto"],["waiting","Waiting","Attente","Espera"],["uncertainty","Uncertainty","Incertitude","Incertidumbre"],["noise","Noise","Bruit","Ruido"],["mess","Mess","Désordre","Desorden"],["pressure","Pressure","Pression","Presión"],["repetition","Repetition","Répétition","Repetición"],["criticism","Criticism","Critique","Crítica"],["delay","Delay","Retard","Retraso"]];
const weakB=[["spiral","Spiral","Spirale","Espiral"],["panic","Panic","Panique","Pánico"],["freeze","Freeze","Blocage","Bloqueo"],["overthink","Overthinking","Surréflexion","Sobrepensamiento"],["avoidance","Avoidance","Évitement","Evitación"],["rage","Rage","Colère","Rabia"],["shutdown","Shutdown","Extinction","Apagado"],["distraction","Distraction","Distraction","Distracción"],["impulse","Impulse","Impulsion","Impulso"],["procrastination","Procrastination","Procrastination","Procrastinación"]];
const abilityA=[["reading","Reading","Lecture","Lectura"],["planning","Planning","Planification","Planificación"],["explaining","Explaining","Explication","Explicación"],["repairing","Repairing","Réparation","Reparación"],["negotiating","Negotiating","Négociation","Negociación"],["learning","Learning","Apprentissage","Aprendizaje"],["organizing","Organizing","Organisation","Organización"],["adapting","Adapting","Adaptation","Adaptación"],["observing","Observing","Observation","Observación"],["prioritizing","Prioritizing","Priorisation","Priorización"],["debugging","Debugging","Débogage","Depuración"],["teaching","Teaching","Enseignement","Enseñanza"],["listening","Listening","Écoute","Escucha"],["estimating","Estimating","Estimation","Estimación"],["coordinating","Coordinating","Coordination","Coordinación"],["simplifying","Simplifying","Simplification","Simplificación"],["inventing","Inventing","Invention","Invención"],["recovering","Recovering","Récupération","Recuperación"]];
const abilityB=[["instinct","Instinct","Instinct","Instinto"],["precision","Precision","Précision","Precisión"],["speed","Speed","Vitesse","Velocidad"],["patience","Patience","Patience","Paciencia"],["improvisation","Improvisation","Improvisation","Improvisación"],["clarity","Clarity","Clarté","Claridad"],["endurance","Endurance","Endurance","Resistencia"],["timing","Timing","Timing","Timing"],["intuition","Intuition","Intuition","Intuición"],["discipline","Discipline","Discipline","Disciplina"]];
const styleA=[["sprint","Sprint","Sprint","Sprint"],["steady","Steady","Régulier","Constante"],["deep_focus","Deep Focus","Concentration profonde","Concentración profunda"],["social","Social","Social","Social"],["night_owl","Night Owl","Oiseau de nuit","Noctámbulo"],["early_bird","Early Bird","Lève-tôt","Madrugador"],["batch","Batch","Par lots","Por lotes"],["reactive","Reactive","Réactif","Reactivo"],["ritual","Ritual","Rituel","Ritual"],["async","Async","Asynchrone","Asíncrono"],["deadline","Deadline","Deadline","Plazo"],["flow","Flow","Flow","Flujo"],["meeting_light","Meeting-Light","Peu de réunions","Pocas reuniones"],["structured","Structured","Structuré","Estructurado"],["experimental","Experimental","Expérimental","Experimental"],["quiet","Quiet","Calme","Tranquilo"],["mobile","Mobile","Mobile","Móvil"],["modular","Modular","Modulaire","Modular"]];
const styleB=[["planner","Planner","Planificateur","Planificador"],["improviser","Improviser","Improvisateur","Improvisador"],["collaborator","Collaborator","Collaborateur","Colaborador"],["soloist","Soloist","Soliste","Solista"],["optimizer","Optimizer","Optimiseur","Optimizador"],["finisher","Finisher","Finisseur","Finalizador"],["explorer","Explorer","Explorateur","Explorador"],["coordinator","Coordinator","Coordinateur","Coordinador"],["maker","Maker","Créateur","Creador"],["reviewer","Reviewer","Relecteur","Revisor"]];
const animalA=[["arctic","Arctic","Arctique","Ártico"],["desert","Desert","Désert","Desértico"],["forest","Forest","Forêt","Bosque"],["mountain","Mountain","Montagne","Montaña"],["river","River","Rivière","Río"],["coastal","Coastal","Côtier","Costero"],["storm","Storm","Tempête","Tormenta"],["midnight","Midnight","Minuit","Medianoche"],["golden","Golden","Doré","Dorado"],["silver","Silver","Argenté","Plateado"],["red","Red","Rouge","Rojo"],["blue","Blue","Bleu","Azul"],["cloud","Cloud","Nuage","Nube"],["urban","Urban","Urbain","Urbano"],["wild","Wild","Sauvage","Salvaje"],["quiet","Quiet","Calme","Tranquilo"]];
const animalB=[["fox","Fox","Renard","Zorro"],["wolf","Wolf","Loup","Lobo"],["owl","Owl","Hibou","Búho"],["otter","Otter","Loutre","Nutria"],["falcon","Falcon","Faucon","Halcón"],["lynx","Lynx","Lynx","Lince"],["bear","Bear","Ours","Oso"],["rabbit","Rabbit","Lapin","Conejo"],["raven","Raven","Corbeau","Cuervo"],["gecko","Gecko","Gecko","Geco"],["dolphin","Dolphin","Dauphin","Delfín"],["turtle","Turtle","Tortue","Tortuga"],["badger","Badger","Blaireau","Tejón"],["heron","Heron","Héron","Garza"]];
let cur=await read("careers"),cand=combos("career",careerA,careerB).map(x=>{const h=hash(x.id),min=24000+h%61000;return{...x,worthPotential:{min,max:min+40000+((h>>>8)%145000)}}});await write("careers",add(cur,cand,targets.careers,"careers"));
for(const [g,p,a,b,k] of [["classes","class",classA,classB,"idealProfile"],["powers","power",powerA,powerB,"idealProfile"],["weaknesses","weakness",weakA,weakB,"lowProfile"],["abilities","ability",abilityA,abilityB,"idealProfile"],["workStyles","workstyle",styleA,styleB,"idealProfile"]]){cur=await read(g);await write(g,add(cur,combos(p,a,b,k),targets[g],g))}
cur=await read("animals");cand=[];for(const a of animalA)for(const b of animalB){const id=`animal_${a[0]}_${b[0]}`;cand.push({id,name:{en:`${a[1]} ${b[1]}`,fr:`${b[2]} ${a[2].toLowerCase()}`,es:`${b[3]} ${a[3].toLowerCase()}`},description:{en:`${a[1]} ${b[1]}: observant, adaptable and unexpectedly determined when it matters.`,fr:`${b[2]} ${a[2].toLowerCase()} : observateur, adaptable et étonnamment déterminé quand ça compte.`,es:`${b[3]} ${a[3].toLowerCase()}: observador, adaptable y sorprendentemente decidido cuando importa.`},idealProfile:profile(id),tags:["expanded_v2","animal"]})}await write("animals",add(cur,cand,targets.animals,"animals"));
cur=await read("synergyRules");cand=[];for(let i=0;i<STATS.length;i++)for(let j=i+1;j<STATS.length;j++){const a=STATS[i],b=STATS[j],h=hash(`${a}:${b}`);cand.push({id:`synergy_${a}_${b}_amplified`,conditions:[{stat:a,op:">=",value:58+h%15},{stat:b,op:">=",value:54+((h>>>5)%19)}],weight:.8+(h%7)*.1,rarityScore:2+h%8,tags:["expanded_v2","amplified"]},{id:`synergy_${a}_${b}_contrast`,conditions:[{stat:a,op:">=",value:60+h%13},{stat:b,op:"<=",value:46-((h>>>7)%14)}],weight:.9+(h%6)*.1,rarityScore:3+((h>>>3)%8),tags:["expanded_v2","contrast"]})}await write("synergyRules",add(cur,cand,targets.synergyRules,"synergyRules"));
console.log("Catalogues V2 OK: careers=200; classes/powers/weaknesses/abilities/workStyles/animals=150; synergies=200");
