import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
const root=resolve(import.meta.dirname,"../.."),dataDir=resolve(root,"src/data"),questionDir=resolve(dataDir,"questions");
const locales=["en","fr","es"],questionFiles=["work","social","life","personality","general"];
const statKeys=new Set(["intelligence","creativity","emotionalControl","empathy","social","communication","ambition","discipline","professionalism","financialSense","risk","luck","energy","humor","chaos"]);
const targets={careers:200,classes:150,powers:150,weaknesses:150,abilities:150,workStyles:150,animals:150};
const readJson=async p=>JSON.parse(await readFile(p,"utf8"));
const load=n=>readJson(resolve(dataDir,`${n}.json`)); const loadQ=n=>readJson(resolve(questionDir,`${n}.json`));
function unique(entries,label){const ids=new Set();for(const e of entries){assert.ok(e?.id,`${label}: id vide`);assert.equal(ids.has(e.id),false,`${label}: id dupliqué ${e.id}`);ids.add(e.id)}return ids}
function localized(v,label){for(const l of locales){assert.equal(typeof v?.[l],"string",`${label}: ${l} manquant`);assert.ok(v[l].trim(),`${label}: ${l} vide`)}}
function profile(v,label){assert.ok(v&&Object.keys(v).length,`${label}: profil vide`);for(const [k,x] of Object.entries(v)){assert.ok(statKeys.has(k),`${label}: stat inconnue ${k}`);assert.ok(Number.isFinite(x)&&x>=0&&x<=100,`${label}.${k}: hors 0..100`)}}
const parts=await Promise.all(questionFiles.map(loadQ));parts.forEach((p,i)=>assert.equal(p.length,30,`${questionFiles[i]}.json: 30 questions requises`));
const questions=parts.flat();assert.equal(questions.length,150,"150 questions requises");unique(questions,"questions");let answers=0;
for(const q of questions){localized(q.text,`question ${q.id}`);assert.equal(q.answers?.length,10,`${q.id}: 10 réponses requises`);unique(q.answers,`answers:${q.id}`);for(const a of q.answers){answers++;localized(a.text,`${q.id}/${a.id}`);for(const [k,v] of Object.entries(a.effects??{})){assert.ok(statKeys.has(k),`${q.id}/${a.id}: stat inconnue ${k}`);assert.ok(Number.isFinite(v),`${q.id}/${a.id}: effet non fini`)}}}
assert.equal(answers,1500,"1500 réponses requises");
const groups=Object.fromEntries(await Promise.all(Object.keys(targets).map(async n=>[n,await load(n)])));
for(const [g,t] of Object.entries(targets)){const entries=groups[g];assert.equal(entries.length,t,`${g}: ${entries.length} au lieu de ${t}`);unique(entries,g);for(const e of entries){localized(e.name??e.text,`${g}.${e.id}`);profile(e.lowProfile??e.idealProfile,`${g}.${e.id}`);if(g==="animals")localized(e.description,`${g}.${e.id}.description`);if(g==="careers")assert.ok(e.worthPotential,`${g}.${e.id}: worthPotential manquant`);if(e.worthPotential){assert.ok(Number.isFinite(e.worthPotential.min)&&Number.isFinite(e.worthPotential.max)&&e.worthPotential.min<=e.worthPotential.max,`${g}.${e.id}: worthPotential invalide`)}}}
const alignments=await load("alignments");assert.equal(alignments.length,9,"9 alignements requis");unique(alignments,"alignments");for(const a of alignments){localized(a.name,`alignment.${a.id}`);localized(a.description,`alignment.${a.id}.description`)}
const synergies=await load("synergyRules");assert.equal(synergies.length,200,`synergies: ${synergies.length} au lieu de 200`);unique(synergies,"synergies");for(const r of synergies){assert.ok(Array.isArray(r.conditions)&&r.conditions.length,`${r.id}: conditions vides`);assert.ok(Number.isFinite(r.weight)&&r.weight>=0,`${r.id}: weight invalide`);assert.ok(Number.isFinite(r.rarityScore)&&r.rarityScore>=0,`${r.id}: rarityScore invalide`);for(const c of r.conditions){assert.ok(statKeys.has(c.stat),`${r.id}: stat inconnue ${c.stat}`);assert.ok([">",">=","<","<=","=="].includes(c.op),`${r.id}: op invalide`);assert.ok(Number.isFinite(c.value),`${r.id}: valeur invalide`)}}
const baselines=await load("matchBaselines");for(const [g,entries] of Object.entries(groups)){const expected=new Set(entries.map(e=>e.id)),actual=baselines[g]??{};assert.equal(Object.keys(actual).length,expected.size,`${g}: couverture baseline non exacte`);for(const id of expected){const b=actual[id];assert.ok(b&&Number.isFinite(b.mean)&&Number.isFinite(b.std)&&b.std>0,`${g}.${id}: baseline invalide`)}}
const calibration=await load("appearanceCalibration");for(const [g,entries] of Object.entries({...groups,alignments})){const expected=new Set(entries.map(e=>e.id)),actual=calibration[g]??{};assert.equal(Object.keys(actual).length,expected.size,`${g}: couverture calibration non exacte`);let sum=0;for(const id of expected){const p=actual[id];assert.ok(Number.isFinite(p)&&p>0&&p<=1,`${g}.${id}: probabilité invalide`);sum+=p}assert.ok(Math.abs(sum-1)<=0.001,`${g}: somme calibration ${sum}`)}
const indexSource=await readFile(resolve(dataDir,"index.ts"),"utf8");for(const token of ["questions.extra","questions.expansion","questions.more","results.extra",".expansion.json","synergyRules.extra","matchBaselines.extra"]){assert.equal(indexSource.includes(token),false,`index.ts contient encore ${token}`)}
console.log(`Content V2 OK: questions=${questions.length}, answers=${answers}, careers=${groups.careers.length}, autres=150, synergies=${synergies.length}, alignments=${alignments.length}`);
